Task 54 15 formik and registration
FedoseevSM/middle.game.praktikum.yandex pull request #9
Opened 2022-10-29 12:00 UTC by DianaIvanovna

54 - Валидация форм с помощью fomik+yup
15 - Верстка страницы регистрации

PS Регулярные выражения + название ошибок взяла из прошлого спринта, их можно по желанию поменять

![image](https://user-images.githubusercontent.com/60156828/198830164-e1fab6bf-4607-4faa-98e5-a17ed8f27e19.png)

2022-10-29 15:03 UTC, Victoriya0993 approved these changes
Все классно, отдельное спасибо за формик и схему валидации!

Небольшой комментарий на перспективу. В файле стилей много вариантов адаптивности шрифта и др. параметров под размер экрана, но при стандартном размере на ноутбуке, компоненты все равно выглядят большими. 
Есть предложение в будущем сделать их поменьше =)

2022-10-29 15:03 UTC, Victoriya0993 commented on packages/client/package.json
> +    "formik": "^2.2.9",
Здорово, что добавила валидацию для инпутов. Спасибо) Я раньше валидацию руками писала, а теперь узнала про эту библиотеку, полезно. 
При добавлении новой зависимости лучше фиксировать ее версию. Можно полностью, зафиксировать, как другие библиотеки здесь. Или использовать ~, чтобы обновлялась только минорная часть

2022-10-29 15:03 UTC, Victoriya0993 commented on packages/client/src/components/Input/Input.tsx
> +    {showError && <p className={styles.error}>{error}</p>}
Очень лаконично записано условие отображения ошибки, круто, беру на заметку

2022-10-29 15:03 UTC, Victoriya0993 commented on packages/client/src/components/Input/types.ts
> -import { InputHTMLAttributes } from 'react';
Можно добавить правило в линт, чтобы при запуске он автоматом убирал везде ";". Чтобы все придерживались примерно одинакового синтаксиса

2022-10-29 15:03 UTC, Victoriya0993 commented on packages/client/src/pages/LoginPage/LoginPage.module.scss
Есть проблема с названием игры, оно "гуляет" по странице (на странице логина и регистрации), при уменьшении окна браузера.

![image](https://user-images.githubusercontent.com/90398540/198838376-cef862c3-0749-4fa7-8150-9854b3a84aca.png)
![image](https://user-images.githubusercontent.com/90398540/198838404-d6753fd3-9619-4214-80e5-436d5d64089a.png)

2022-10-29 16:04 UTC, DianaIvanovna commented on packages/client/src/components/Input/types.ts
> -import { InputHTMLAttributes } from 'react';
у меня сейчас при сохранении файла и так автоматически убирает  ";"

2022-10-29 19:02 UTC, samgxlden commented on packages/client/src/components/Input/types.ts
> -import { InputHTMLAttributes } from 'react';
@Victoriya0993 Зачем убирать все ;? Это дурной тон

2022-10-29 19:03 UTC, samgxlden commented on packages/client/src/components/Input/types.ts
> -import { InputHTMLAttributes } from 'react';
@DianaIvanovna Предлагаю добавить в prettier правило, чтобы ; всегда проставлялись

2022-10-29 19:46 UTC, samgxlden requested changes
Вероятно то, что стилями компонентов удобнее управлять из самого компонента, а не со страницы

2022-10-29 19:46 UTC, samgxlden commented on packages/client/src/components/Button/Button.tsx
> +    className={cn(styles.button, className)}
```suggestion
    className={cn(styles.button, className)}

```

```
export const Button: React.FC<Props> = ({
  children,
  type = 'button',
  onClick,
  color
}: Props): JSX.Element => (
  <button
    className={cn(styles.button, styles[color])}
    onClick={onClick}
    type={type}>
    {children}
  </button>
)
```

2022-10-29 19:46 UTC, samgxlden commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +              <Button className={styles.form_button} type="submit">
```suggestion
              <Button className={styles.form_button} type="submit">
```

              <Button color="regular" type="submit">
                <h1 className={styles.login_button_title}>Sign in</h1>
              </Button>

2022-10-29 19:51 UTC, samgxlden commented on packages/client/src/components/Button/Button.tsx
> +    className={cn(styles.button, className)}
В стили компонента нужно перенести класс и назвать, например regular, так как может будут круглые кнопки, например rounded или еще какие-то
`.regular {
    background-color: $main_input_bg_color;
    border: $main_button_border_color;
    height: 84px;
    position: absolute;
    top: 0px;
    left: 0px;
    right: 0px;
    cursor: pointer;
    box-shadow: inset -6px 0px 2px #222a5c, inset 6px 0px 4px #222a5c,
      inset 0px -6px 4px #38002c, inset 0px 8px 2px rgba(255, 255, 255, 0.46);
  }`

2022-10-29 19:55 UTC, samgxlden commented on packages/client/src/components/Button/Button.tsx
> +    className={cn(styles.button, className)}
@DianaIvanovna чтобы убрать битые кнопки, например, добавь к стилю кнопки `width: 100%;` или сетку

2022-10-30 12:02 UTC, samgxlden commented on packages/client/src/pages/Forum/Forum.tsx
> +          <Button className="button_width_100">GO BACK</Button>
Нам вообще не нужен класс button_width_100, если в классе block_buttons_top указать
```
.block_buttons_top {
  display: grid;
  grid-template-columns: repeat(2, auto ); 
  gap: 10px;
}
```

2022-10-30 12:14 UTC, samgxlden approved these changes

2022-10-30 12:16 UTC, samgxlden commented on packages/client/src/pages/Forum/Forum.tsx
> +          <Button className="button_width_100">GO BACK</Button>
@DianaIvanovna внеси, пожалуйста, правки по классам. остальное все нормально, после правок сразу сливай pr

2022-10-30 12:16 UTC, merged

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Button/types.ts
>  export interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
Для чего везде используется `extends ButtonHTMLAttributes`?  Обычно пишут максимально суженный тип из того, что реально используется

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Button/types.ts
> +  type?: 'button' | 'submit' | 'reset' | undefined
Зачем и `? и undefined`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Form/Form.tsx
> +import React from 'react'
```suggestion
import React, {FC} from 'react'

```

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Form/types.ts
> +  children: ReactNode
Если вы используете FC, то незачем описывать children он и так есть в типе FC

А вообще, есть еще вот такая штука для [размышления](https://github.com/facebook/create-react-app/pull/8177)

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Input/Input.tsx
> +  ...props
Не стоит использовать спрединг пропсов - это в некотором смысле антипаттерн, очень сложно потом разбираться, что реально используется, а что нет

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Input/types.ts
> +  onChange?: (e: React.ChangeEvent<any>) => void
Кажется странным, что для инпута onChange и value - опциональные значения

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Input/types.ts
> +  error?: string | undefined
Все еще не очень понимаю, зачем в этом случае использовать и `? и undefined`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/constants/Schemas.ts
> +import * as Yup from 'yup'
Стоит добавить `"@types/yup"`

Что бы можно было вот так: ` import { object } from 'yup';`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Input/index.ts
> +import { Input } from './Input'
Я бы предпочел использовать именованные импорты, имхо так удобнее:
`export {Input} from './Input';`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/main.tsx
> +          path="/forum"
Думаю можно вынести роуты в конфижек, так если этот url понадобится где-то еще, то можно будет взять его из констант)

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
>  // import Button from './components/Button/Button';
Законменченный код принято удалять

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
> +          <>
Лучше по честному обернуть в компонент, а лучше вынести в отдельный - "TopicList" к примеру

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
> +  const newTopic = () => {
- не очень очевидный нейминг, не понятно из названия, что эта функиця делат. 
- Функции, который передаются в другие компоненты стоит оборачивать в useCallback, что бы иметь постоянную на эту функцию;

`const handleCreateNewTopic = useCallback(() => setOpen(isOpen => !isOpen), []);`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
> +            <div className={styles.block_footer}>1, 2, 3, 4, 5 ...</div>
Все тексты я бы тоже вынес в отдельный файл. Помимо единого источника правды с отдельным файлом проще будет делать локализацию при необходимости https://react.i18next.com/

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
> +            showError={!!errors.confirmPassword && !!touched.confirmPassword}
Явно приведение к Boolean мне кажется получается более наглядным `Boolean(errors.confirmPassword)`

2022-10-30 13:19 UTC, khitrind commented on packages/client/src/components/Input/Input.tsx
>  }: Props): JSX.Element => (
`FC` так же описывает возвращаемый тип компонента